[tool.poetry]
name = "etl-components"
version = "1.2.4"
description = "Components to build ETL pipelines using pandas and psycopg or sqlite"
authors = ["Luc Heuff <10941592+LucHeuff@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "etl_components"}]


[tool.poetry.dependencies]
python = "^3.12"
psycopg = "^3.1.18"


[tool.poetry.group.dev.dependencies]
ipython = "^8.22.1"
ruff = "^0.2.2"
neovim = "^0.3.1"
pytest = "^8.0.1"
hypothesis = "^6.98.10"
poetry2setup = "^1.1.0"
polars = "^0.20.31"
pandas = "^2.2.2"

[tool.ruff]
line-length = 80

[tool.ruff.lint]
select = [
    "F", "C90", "I", "N", "D", "ANN", "BLE", "FBT", "B", "A", "C4", "EM",
    "ICN", "LOG", "G", "INP", "PIE", "T20", "PYI", "PT", "RSE", "RET", "SLF",
    "SIM", "ARG", "FIX", "ERA", "PD", "PL", "TRY", "PERF", "RUF"
]
ignore = ["ANN101", "PLR09", "D100", "D201", "D203", "D213", "F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
