[tool.poetry]
name = "etl-components"
version = "1.0.2"
description = "Components to build ETL pipelines using pandas and psycopg or sqlite"
authors = ["Luc Heuff <10941592+LucHeuff@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "etl_components"}]


[tool.poetry.dependencies]
python = "^3.12"
psycopg = "^3.1.18"
pandas = "^2.2.0"
python-dotenv = "^1.0.1"


[tool.poetry.group.dev.dependencies]
ipython = "^8.22.1"
ruff = "^0.2.2"
neovim = "^0.3.1"
pytest = "^8.0.1"
hypothesis = "^6.98.10"
poetry2setup = "^1.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
